name = "siren"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true
workers_dev = true

routes = [
  { pattern = "joss.checker-ip.xyz", custom_domain = true },
  { pattern = "ava.game.naver.com.joss.checker-ip.xyz", custom_domain = true },
  { pattern = "df.game.naver.com.joss.checker-ip.xyz", custom_domain = true },
  { pattern = "graph.instagram.com.joss.checker-ip.xyz", custom_domain = true },
  { pattern = "zaintest.vuclip.com.joss.checker-ip.xyz", custom_domain = true },
  { pattern = "support.zoom.us.joss.checker-ip.xyz", custom_domain = true },
  { pattern = "cache.netflix.com.joss.checker-ip.xyz", custom_domain = true }
]

[[kv_namespaces]]
binding = "SIREN"
id = "86850fea3b424ad0b4cedcdbb292969b"

[build]
command = "cargo install -q worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install -q worker-build && worker-build --dev" }

[vars]

UUID = "f282b878-8711-45a1-8c69-5564172123c1"

MAIN_PAGE_URL = "https://raw.githubusercontent.com/jaka2m/vpn-cf/refs/heads/master/web/index.html"
SUB_PAGE_URL  = "https://raw.githubusercontent.com/jaka2m/vpn-cf/refs/heads/master/web/sub.html"
LINK_PAGE_URL = "https://raw.githubusercontent.com/jaka2m/vpn-cf/refs/heads/master/web/link.html"
CONVERTER_PAGE_URL = "https://raw.githubusercontent.com/jaka2m/vpn-cf/refs/heads/master/web/converter.html"
